module MAGEMin_C

using MAGEMin_jll

# Load autogenerated library
include("../gen/magemin_library.jl") 
export LibMAGEMin

# Load julia-style wrappers 
include("../julia/MAGEMin_wrappers.jl")



end # module
